#A module that implements the various outputs.
#Each kind of output that can be generated by
#the program must be implemented as a separate class


def get_lat_lng_collection(search_result_dict: dict)->[[]]:
    lat_lng_collection=[] 
    for item in search_result_dict['route']['locations']:
        lat_lng=[]
        lat=item['latLng']['lat']
        lng=item['latLng']['lng']
        lat_lng.append(lat)
        lat_lng.append(lng)
        lat_lng_collection.append(lat_lng)
    return lat_lng_collection


class LatLng:
    def display_output(self, search_result_dict):
        print('LATLONGS')
        for item in search_result_dict['route']['locations']:
            lat=item['latLng']['lat']
            lng=item['latLng']['lng']
            lat_str="{0:.2f}".format(round(lat,2))
            lng_str="{0:.2f}".format(round(lng,2))
            if 0<=lat<90:
                lat_str+='N'
            else:
                lat_str+='S'
                lat_str=lat_str[1:]
            if 0<=int(lng)<180:
                lng_str+='E'
            else:
                lng_str+='W'
                lng_str=lng_str[1:]
            print(lat_str+' '+lng_str)

class Directions:
    def display_output(self,search_result_dict):
        print('DIRECTIONS')
        for item in search_result_dict['route']['legs']:
            for indice in item['maneuvers']:
                print(indice['narrative'])

class TotalTime:
    def display_output(self,search_result_dict):
        print('TOTAL TIME:', end=' ')
        print(int(round(search_result_dict['route']['time']/60)), end=' minutes')
        print()

class Distance:
    def display_output(self, search_result_dict):
        print('TOTAL DISTANCE: ',end='')
        print(int(round(search_result_dict['route']['distance'])), end=' miles')
        print()
            
class Elevation:
    def display_output(self, search_result_dict):
        for item in search_result_dict['elevationProfile']:
            print(int(round(item['height']*3.28084)))
        
            
            
        
